lang: en
title: SIGILLatum
description: Petr Tesarik's Linux blog
author: Petr Tesařík
email: ptesarik@suse.com
logo: /assets/sigill.png
url: "https://SIGILLatum.tesarici.cz"
github_url: "https://github.com/ptesarik/SIGILLatum.github.io"

remote_theme: pages-themes/minimal

# markdown render engine.
markdown_ext: md,mdwn
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

exclude: [README.md, Gemfile, Gemfile.lock, vendor]
