#!/bin/sh
exec ldapsearch -Y EXTERNAL -s one -b ou=users,dc=example,dc=com \
    '(&(objectClass=ldapPublicKey)(uid='"$1"'))' 'sshPublicKey' | \
    sed -n '/^ /{H;d};/sshPublicKey:/x;$g;s/\n *//g;s/sshPublicKey: //gp'
